services:

  streamlit:

    build:
      context: .
      dockerfile: Dockerfile

    container_name: streamlit-dashboard
    working_dir: /streamlit-dashboard

    ports:
      - "8501:8501"

    volumes:
      - ./:/streamlit-dashboard

    environment:
      STREAMLIT_SERVER_HEADLESS: "true"
      STREAMLIT_BROWSER_GATHER_USAGE_STATS: "false"

    restart: unless-stopped
